export const SENSORY_AXIS_IDS = [
  'character',
  'space',
  'echo',
  'grain',
  'dirt',
  'tight',
  'mod',
  'drift',
  'pan',
  'veil',
  'halo',
  'well',
  'bloom',
  'plate',
  'spring',
  'shimmer',
  'reverse',
  'gate',
  'fuzz',
  'crush',
  'tape',
  'fold',
  'vinyl',
  'sweep',
] as const

export type SensoryAxisId = (typeof SENSORY_AXIS_IDS)[number]

export type SensoryAxisKind = 'bipolar' | 'unipolar'

export type SensoryAxisDef = {
  id: SensoryAxisId
  kind: SensoryAxisKind
  /** DSP module this control owns. */
  module: 'eq' | 'reverb' | 'delay' | 'grain' | 'distortion' | 'compressor' | 'gain' | 'filter'
  negativeLabel: string
  positiveLabel: string
  ariaLabel: string
  hint: string
}

export const SENSORY_AXES: Record<SensoryAxisId, SensoryAxisDef> = {
  character: {
    id: 'character',
    kind: 'bipolar',
    module: 'eq',
    negativeLabel: 'tight',
    positiveLabel: 'open',
    ariaLabel: 'Character, tight to open. Morphs EQ only.',
    hint: 'shape the tone',
  },
  space: {
    id: 'space',
    kind: 'unipolar',
    module: 'reverb',
    negativeLabel: 'close',
    positiveLabel: 'vast',
    ariaLabel: 'Space, close to vast. Morphs reverb only.',
    hint: 'open the room',
  },
  echo: {
    id: 'echo',
    kind: 'unipolar',
    module: 'delay',
    negativeLabel: 'dry',
    positiveLabel: 'echo',
    ariaLabel: 'Echo, dry to echo. Morphs delay only.',
    hint: 'let it repeat',
  },
  grain: {
    id: 'grain',
    kind: 'unipolar',
    module: 'grain',
    negativeLabel: 'solid',
    positiveLabel: 'grain',
    ariaLabel: 'Grain, solid to layered. Morphs grain only.',
    hint: 'break into grains',
  },
  dirt: {
    id: 'dirt',
    kind: 'unipolar',
    module: 'distortion',
    negativeLabel: 'clean',
    positiveLabel: 'dirt',
    ariaLabel: 'Dirt, clean to grit. Morphs distortion only.',
    hint: 'add grit',
  },
  tight: {
    id: 'tight',
    kind: 'unipolar',
    module: 'compressor',
    negativeLabel: 'open',
    positiveLabel: 'tight',
    ariaLabel: 'Tight, open to compressed. Morphs compressor only.',
    hint: 'squeeze it closer',
  },
  mod: {
    id: 'mod',
    kind: 'unipolar',
    module: 'grain',
    negativeLabel: 'still',
    positiveLabel: 'mod',
    ariaLabel: 'Mod, still to modulated. Morphs grain motion only.',
    hint: 'let it breathe',
  },
  drift: {
    id: 'drift',
    kind: 'unipolar',
    module: 'delay',
    negativeLabel: 'center',
    positiveLabel: 'drift',
    ariaLabel: 'Drift, centered to moving stereo. Morphs delay image only.',
    hint: 'move it in the panorama',
  },
  pan: {
    id: 'pan',
    kind: 'unipolar',
    module: 'gain',
    negativeLabel: 'still',
    positiveLabel: 'pan',
    ariaLabel: 'Pan, still to orbiting. Morphs input pan LFO only.',
    hint: 'swing left and right',
  },
  veil: {
    id: 'veil',
    kind: 'unipolar',
    module: 'reverb',
    negativeLabel: 'clear',
    positiveLabel: 'veil',
    ariaLabel: 'Veil, clear to distant. Morphs reverb, delay, and EQ together.',
    hint: 'draw a dark curtain',
  },
  halo: {
    id: 'halo',
    kind: 'unipolar',
    module: 'reverb',
    negativeLabel: 'bare',
    positiveLabel: 'halo',
    ariaLabel: 'Halo, bare to blooming. Morphs reverb, delay, and EQ together.',
    hint: 'let air bloom around it',
  },
  well: {
    id: 'well',
    kind: 'unipolar',
    module: 'eq',
    negativeLabel: 'flat',
    positiveLabel: 'well',
    ariaLabel: 'Well, flat to hollow. Morphs EQ, reverb, and delay together.',
    hint: 'drop it into a cavity',
  },
  bloom: {
    id: 'bloom',
    kind: 'unipolar',
    module: 'reverb',
    negativeLabel: 'still',
    positiveLabel: 'bloom',
    ariaLabel: 'Bloom, still to rising cloud. Morphs bloom reverb.',
    hint: 'let the cloud rise',
  },
  plate: {
    id: 'plate',
    kind: 'unipolar',
    module: 'reverb',
    negativeLabel: 'dry',
    positiveLabel: 'plate',
    ariaLabel: 'Plate, dry to studio plate. Morphs plate reverb.',
    hint: 'shine a plate',
  },
  spring: {
    id: 'spring',
    kind: 'unipolar',
    module: 'reverb',
    negativeLabel: 'solid',
    positiveLabel: 'spring',
    ariaLabel: 'Spring, solid to twang. Morphs spring reverb.',
    hint: 'twang the tank',
  },
  shimmer: {
    id: 'shimmer',
    kind: 'unipolar',
    module: 'reverb',
    negativeLabel: 'grounded',
    positiveLabel: 'shimmer',
    ariaLabel: 'Shimmer, grounded to octave bloom. Morphs shimmer reverb.',
    hint: 'lift an octave',
  },
  reverse: {
    id: 'reverse',
    kind: 'unipolar',
    module: 'reverb',
    negativeLabel: 'forward',
    positiveLabel: 'reverse',
    ariaLabel: 'Reverse, forward to swell. Morphs reverse reverb.',
    hint: 'swell into the hit',
  },
  gate: {
    id: 'gate',
    kind: 'unipolar',
    module: 'reverb',
    negativeLabel: 'open',
    positiveLabel: 'gate',
    ariaLabel: 'Gate, open to chopped tail. Morphs gated reverb.',
    hint: 'chop the tail',
  },
  fuzz: {
    id: 'fuzz',
    kind: 'unipolar',
    module: 'distortion',
    negativeLabel: 'clean',
    positiveLabel: 'fuzz',
    ariaLabel: 'Fuzz, clean to wool. Morphs fuzz distortion.',
    hint: 'wool the edges',
  },
  crush: {
    id: 'crush',
    kind: 'unipolar',
    module: 'distortion',
    negativeLabel: 'smooth',
    positiveLabel: 'crush',
    ariaLabel: 'Crush, smooth to bitcrush. Morphs bitcrush distortion.',
    hint: 'break the bits',
  },
  tape: {
    id: 'tape',
    kind: 'unipolar',
    module: 'distortion',
    negativeLabel: 'clean',
    positiveLabel: 'tape',
    ariaLabel: 'Tape, clean to saturated tape. Morphs tape distortion.',
    hint: 'push the tape',
  },
  fold: {
    id: 'fold',
    kind: 'unipolar',
    module: 'distortion',
    negativeLabel: 'linear',
    positiveLabel: 'fold',
    ariaLabel: 'Fold, linear to wavefold. Morphs wavefold distortion.',
    hint: 'fold the wave',
  },
  vinyl: {
    id: 'vinyl',
    kind: 'unipolar',
    module: 'distortion',
    negativeLabel: 'clean',
    positiveLabel: 'vinyl',
    ariaLabel: 'Vinyl, clean to dusty record. Morphs vinyl distortion.',
    hint: 'add record dust',
  },
  sweep: {
    id: 'sweep',
    kind: 'unipolar',
    module: 'filter',
    negativeLabel: 'open',
    positiveLabel: 'sweep',
    ariaLabel: 'Sweep, open to moving filter. Morphs FILTER only.',
    hint: 'move the filter',
  },
}

export const PRIMARY_ORBIT_AXES: SensoryAxisId[] = [
  'character',
  'space',
  'echo',
  'grain',
  'dirt',
  'tight',
  'mod',
  'drift',
  'pan',
  'veil',
  'halo',
  'well',
  'bloom',
  'plate',
  'spring',
  'shimmer',
  'reverse',
  'gate',
  'fuzz',
  'crush',
  'tape',
  'fold',
  'vinyl',
  'sweep',
]

export const SECONDARY_FIELD_AXES: SensoryAxisId[] = []

export type SensoryDialPole = 'pos' | 'neg'

export type SensoryDialSpec = {
  axis: SensoryAxisId
  pole: SensoryDialPole
  kind?: 'unipolar' | 'bipolar'
  label: string
  negativeLabel?: string
  positiveLabel?: string
  whisper: string
  tone: 'warm' | 'cool'
  ariaLabel?: string
}

/** Feeling dials. Each control is a from–to pair owned by one effect. */
export const SENSORY_DIALS: readonly SensoryDialSpec[] = [
  {
    axis: 'character',
    pole: 'pos',
    kind: 'bipolar',
    label: 'character',
    negativeLabel: 'tight',
    positiveLabel: 'open',
    whisper: 'tight to open',
    tone: 'warm',
    ariaLabel: 'Character, tight to open',
  },
  {
    axis: 'space',
    pole: 'pos',
    kind: 'unipolar',
    label: 'space',
    negativeLabel: 'close',
    positiveLabel: 'vast',
    whisper: 'close to vast',
    tone: 'cool',
    ariaLabel: 'Space, close to vast',
  },
  {
    axis: 'echo',
    pole: 'pos',
    kind: 'unipolar',
    label: 'echo',
    negativeLabel: 'dry',
    positiveLabel: 'echo',
    whisper: 'dry to echo',
    tone: 'cool',
    ariaLabel: 'Echo, dry to echo',
  },
  {
    axis: 'grain',
    pole: 'pos',
    kind: 'unipolar',
    label: 'grain',
    negativeLabel: 'solid',
    positiveLabel: 'grain',
    whisper: 'solid to grain',
    tone: 'cool',
    ariaLabel: 'Grain, solid to layered',
  },
  {
    axis: 'dirt',
    pole: 'pos',
    kind: 'unipolar',
    label: 'dirt',
    negativeLabel: 'clean',
    positiveLabel: 'dirt',
    whisper: 'clean to dirt',
    tone: 'warm',
    ariaLabel: 'Dirt, clean to grit',
  },
  {
    axis: 'tight',
    pole: 'pos',
    kind: 'unipolar',
    label: 'tight',
    negativeLabel: 'open',
    positiveLabel: 'tight',
    whisper: 'open to tight',
    tone: 'warm',
    ariaLabel: 'Tight, open to compressed',
  },
  {
    axis: 'mod',
    pole: 'pos',
    kind: 'unipolar',
    label: 'mod',
    negativeLabel: 'still',
    positiveLabel: 'mod',
    whisper: 'still to modulated',
    tone: 'cool',
    ariaLabel: 'Mod, still to modulated',
  },
  {
    axis: 'drift',
    pole: 'pos',
    kind: 'unipolar',
    label: 'drift',
    negativeLabel: 'center',
    positiveLabel: 'drift',
    whisper: 'center to panorama',
    tone: 'cool',
    ariaLabel: 'Drift, centered to moving stereo',
  },
  {
    axis: 'pan',
    pole: 'pos',
    kind: 'unipolar',
    label: 'pan',
    negativeLabel: 'still',
    positiveLabel: 'pan',
    whisper: 'still to orbiting pan',
    tone: 'cool',
    ariaLabel: 'Pan, still to orbiting',
  },
  {
    axis: 'veil',
    pole: 'pos',
    kind: 'unipolar',
    label: 'veil',
    negativeLabel: 'clear',
    positiveLabel: 'veil',
    whisper: 'clear to distant',
    tone: 'cool',
    ariaLabel: 'Veil, clear to distant',
  },
  {
    axis: 'halo',
    pole: 'pos',
    kind: 'unipolar',
    label: 'halo',
    negativeLabel: 'bare',
    positiveLabel: 'halo',
    whisper: 'bare to blooming',
    tone: 'cool',
    ariaLabel: 'Halo, bare to blooming',
  },
  {
    axis: 'well',
    pole: 'pos',
    kind: 'unipolar',
    label: 'well',
    negativeLabel: 'flat',
    positiveLabel: 'well',
    whisper: 'flat to hollow',
    tone: 'warm',
    ariaLabel: 'Well, flat to hollow',
  },
  {
    axis: 'bloom',
    pole: 'pos',
    kind: 'unipolar',
    label: 'bloom',
    negativeLabel: 'still',
    positiveLabel: 'bloom',
    whisper: 'still to cloud',
    tone: 'cool',
    ariaLabel: 'Bloom, still to rising cloud',
  },
  {
    axis: 'plate',
    pole: 'pos',
    kind: 'unipolar',
    label: 'plate',
    negativeLabel: 'dry',
    positiveLabel: 'plate',
    whisper: 'dry to plate',
    tone: 'warm',
    ariaLabel: 'Plate, dry to studio plate',
  },
  {
    axis: 'spring',
    pole: 'pos',
    kind: 'unipolar',
    label: 'spring',
    negativeLabel: 'solid',
    positiveLabel: 'spring',
    whisper: 'solid to twang',
    tone: 'warm',
    ariaLabel: 'Spring, solid to twang',
  },
  {
    axis: 'shimmer',
    pole: 'pos',
    kind: 'unipolar',
    label: 'shimmer',
    negativeLabel: 'grounded',
    positiveLabel: 'shimmer',
    whisper: 'grounded to octave bloom',
    tone: 'cool',
    ariaLabel: 'Shimmer, grounded to octave bloom',
  },
  {
    axis: 'reverse',
    pole: 'pos',
    kind: 'unipolar',
    label: 'reverse',
    negativeLabel: 'forward',
    positiveLabel: 'reverse',
    whisper: 'forward to swell',
    tone: 'cool',
    ariaLabel: 'Reverse, forward to swell',
  },
  {
    axis: 'gate',
    pole: 'pos',
    kind: 'unipolar',
    label: 'gate',
    negativeLabel: 'open',
    positiveLabel: 'gate',
    whisper: 'open to chopped tail',
    tone: 'warm',
    ariaLabel: 'Gate, open to chopped tail',
  },
  {
    axis: 'fuzz',
    pole: 'pos',
    kind: 'unipolar',
    label: 'fuzz',
    negativeLabel: 'clean',
    positiveLabel: 'fuzz',
    whisper: 'clean to wool',
    tone: 'warm',
    ariaLabel: 'Fuzz, clean to wool',
  },
  {
    axis: 'crush',
    pole: 'pos',
    kind: 'unipolar',
    label: 'crush',
    negativeLabel: 'smooth',
    positiveLabel: 'crush',
    whisper: 'smooth to bitcrush',
    tone: 'warm',
    ariaLabel: 'Crush, smooth to bitcrush',
  },
  {
    axis: 'tape',
    pole: 'pos',
    kind: 'unipolar',
    label: 'tape',
    negativeLabel: 'clean',
    positiveLabel: 'tape',
    whisper: 'clean to tape',
    tone: 'warm',
    ariaLabel: 'Tape, clean to saturated tape',
  },
  {
    axis: 'fold',
    pole: 'pos',
    kind: 'unipolar',
    label: 'fold',
    negativeLabel: 'linear',
    positiveLabel: 'fold',
    whisper: 'linear to wavefold',
    tone: 'cool',
    ariaLabel: 'Fold, linear to wavefold',
  },
  {
    axis: 'vinyl',
    pole: 'pos',
    kind: 'unipolar',
    label: 'vinyl',
    negativeLabel: 'clean',
    positiveLabel: 'vinyl',
    whisper: 'clean to dusty record',
    tone: 'warm',
    ariaLabel: 'Vinyl, clean to dusty record',
  },
  {
    axis: 'sweep',
    pole: 'pos',
    kind: 'unipolar',
    label: 'sweep',
    negativeLabel: 'open',
    positiveLabel: 'sweep',
    whisper: 'open to moving filter',
    tone: 'cool',
    ariaLabel: 'Sweep, open to moving filter',
  },
]
