import { PARAMS } from '../audio/parameters/definitions'
import type { ParamId } from '../audio/parameters/types'
import type { Locale, LocalizedText } from '../i18n/locale'
import type { SensoryAxisId } from '../sensory/sensoryParameters'

const d = (en: string, pl: string): LocalizedText => ({ en, pl })

const EQ_BANDS = [1, 2, 3, 4, 5, 6, 7, 8] as const

function eqBandEntries(): Record<string, LocalizedText> {
  const out: Record<string, LocalizedText> = {}
  for (const n of EQ_BANDS) {
    out[`eq${n}Freq`] = d(
      `Sets the center frequency of EQ band ${n}.`,
      `Ustawia częstotliwość środkową pasma EQ ${n}.`,
    )
    out[`eq${n}Gain`] = d(
      `Boosts or cuts the level of EQ band ${n}.`,
      `Podbija lub tłumi poziom pasma EQ ${n}.`,
    )
    out[`eq${n}Q`] = d(
      `Sets how wide or narrow EQ band ${n} is.`,
      `Ustawia szerokość pasma EQ ${n}.`,
    )
  }
  return out
}

export const PARAM_DESCRIPTIONS: Record<ParamId, LocalizedText> = {
  start: d('Sets where playback of the selected region begins.', 'Ustawia początek odtwarzania zaznaczonego obszaru.'),
  end: d('Sets where playback of the selected region ends.', 'Ustawia koniec odtwarzania zaznaczonego obszaru.'),
  speed: d('Changes playback speed without using this as a display-only control.', 'Zmienia prędkość odtwarzania próbki.'),
  pitch: d('Shifts the musical pitch of the sample in semitones.', 'Przesuwa wysokość dźwięku próbki w półtonach.'),
  stretchInterp: d('Controls overlap used when speed or pitch leave the original rate.', 'Określa nakładanie się ziaren przy zmianie prędkości lub wysokości.'),
  stretchInterpOn: d('Turns time-stretch interpolation on or off.', 'Włącza lub wyłącza interpolację przy zmianie tempa.'),
  stretchInterpAlgo: d('Chooses the interpolation algorithm for pitch and speed changes.', 'Wybiera algorytm interpolacji przy zmianie wysokości i prędkości.'),
  gain: d('Adjusts the input signal level.', 'Reguluje poziom sygnału wejściowego.'),
  pan: d('Places the signal in the stereo field from left to right.', 'Umieszcza sygnał w polu stereo od lewej do prawej.'),
  channelGainL: d('Sets the left channel level of the input.', 'Ustawia poziom lewego kanału wejścia.'),
  channelGainR: d('Sets the right channel level of the input.', 'Ustawia poziom prawego kanału wejścia.'),
  makeMono: d('Sums the input to mono.', 'Sumuje wejście do mono.'),
  invertPhase: d('Inverts the polarity of the input signal.', 'Odwraca polaryzację sygnału wejściowego.'),
  grainSize: d('Sets the length of each grain window.', 'Ustawia długość każdego ziarna.'),
  density: d('Sets how many grains are triggered per second.', 'Ustawia liczbę ziaren uruchamianych na sekundę.'),
  position: d('Sets the read position inside the selected region.', 'Ustawia pozycję odczytu w zaznaczonym obszarze.'),
  scatter: d('Spreads grain start times around the read position.', 'Rozrzuca początki ziaren wokół pozycji odczytu.'),
  grainPitch: d('Offsets the pitch of grains in semitones.', 'Przesuwa wysokość ziaren w półtonach.'),
  pitchSpread: d('Randomizes grain pitch around the grain pitch setting.', 'Losowo rozrzuca wysokość ziaren wokół ustawionej wartości.'),
  filterCutoff: d('Sets the filter cutoff frequency.', 'Ustawia częstotliwość odcięcia filtra.'),
  filterReso: d('Sets how strongly the filter emphasizes the cutoff.', 'Ustawia, jak mocno filtr podkreśla częstotliwość odcięcia.'),
  filterDrive: d('Adds gain into the filter for saturation and bite.', 'Dodaje wzmocnienie przed filtrem, nasycając brzmienie.'),
  filterMix: d('Blends the filtered signal with the unfiltered signal.', 'Miesza sygnał przefiltrowany z nieprzefiltrowanym.'),
  filterKind: d('Chooses the filter type, such as low-pass or high-pass.', 'Wybiera typ filtra, na przykład dolnoprzepustowy lub górnoprzepustowy.'),
  filterSlope: d('Sets how steep the filter rolloff is.', 'Ustawia stromość zbocza filtra.'),
  filterCharacter: d('Morphs the filter voicing and resonance character.', 'Zmienia charakter i rezonans filtra.'),
  filterMorph: d('Crossfades between filter responses.', 'Przeplata odpowiedzi filtra.'),
  filterLfoRate: d('Sets how fast the filter LFO moves.', 'Ustawia prędkość LFO filtra.'),
  filterLfoDepth: d('Sets how far the filter LFO sweeps the cutoff.', 'Ustawia zakres modulacji odcięcia przez LFO filtra.'),
  filterLfoShape: d('Chooses the filter LFO waveform.', 'Wybiera kształt fali LFO filtra.'),
  filterLfoSync: d('Locks the filter LFO rate to tempo.', 'Synchronizuje LFO filtra z tempem.'),
  filterLfoNote: d('Sets the synced note length of the filter LFO.', 'Ustawia długość nuty zsynchronizowanego LFO filtra.'),
  filterLfoNoteKind: d('Chooses dotted or triplet note values for the filter LFO.', 'Wybiera wartości nutowe z kropką lub triole dla LFO filtra.'),
  filterEnvAmt: d('How much the envelope moves the filter cutoff.', 'Określa, jak mocno obwiednia przesuwa odcięcie filtra.'),
  filterEnvAttack: d('Sets how quickly the filter envelope opens.', 'Ustawia, jak szybko obwiednia filtra narasta.'),
  filterEnvRelease: d('Sets how quickly the filter envelope closes.', 'Ustawia, jak szybko obwiednia filtra opada.'),
  filterEnvDir: d('Chooses whether the envelope opens or closes the filter.', 'Wybiera, czy obwiednia otwiera, czy zamyka filtr.'),
  filterAdsAmt: d('How much the ADSR envelope moves the filter.', 'Określa, jak mocno obwiednia ADSR steruje filtrem.'),
  filterAdsAttack: d('Attack time of the filter ADSR envelope.', 'Czas ataku obwiedni ADSR filtra.'),
  filterAdsDecay: d('Decay time of the filter ADSR envelope.', 'Czas opadania obwiedni ADSR filtra.'),
  filterAdsSustain: d('Sustain level of the filter ADSR envelope.', 'Poziom podtrzymania obwiedni ADSR filtra.'),
  filterAdsRelease: d('Release time of the filter ADSR envelope.', 'Czas zwolnienia obwiedni ADSR filtra.'),
  filterPitchTrack: d('Tracks the filter cutoff with the sample pitch.', 'Śledzi odcięcie filtra wraz z wysokością próbki.'),
  delayDry: d('Sets the unprocessed delay input level on the left or mono path.', 'Ustawia poziom suchego sygnału delay na ścieżce lewej lub mono.'),
  delayDryR: d('Sets the unprocessed delay input level on the right path.', 'Ustawia poziom suchego sygnału delay na ścieżce prawej.'),
  delayWet: d('Sets the delayed signal level on the left or mono path.', 'Ustawia poziom opóźnionego sygnału na ścieżce lewej lub mono.'),
  delayWetR: d('Sets the delayed signal level on the right path.', 'Ustawia poziom opóźnionego sygnału na ścieżce prawej.'),
  delayCorrelate: d('Links delay Dry and Wet so they stay complementary. Turn it off to set the two levels independently.', 'Łączy Dry i Wet delay tak, by zawsze uzupełniały się do 100%. Wyłącz, by ustawiać poziomy niezależnie.'),
  delayOutput: d('Sets the overall delay module output level.', 'Ustawia ogólny poziom wyjściowy modułu delay.'),
  delayTime: d('Sets the left or mono delay time.', 'Ustawia czas opóźnienia lewego lub mono.'),
  delayTimeR: d('Sets the right delay time.', 'Ustawia czas opóźnienia prawego.'),
  delayFeedback: d('Controls the amount of delayed signal fed back into the delay.', 'Określa ilość sygnału delay zawracanego ponownie na wejście efektu.'),
  delayFeedbackR: d('Controls feedback of the right delay line.', 'Określa ilość sygnału zawracanego w prawej linii delay.'),
  delayStereo: d('Sets the stereo spread of the delay.', 'Ustawia szerokość stereo efektu delay.'),
  reverbDry: d('Sets the unprocessed signal level through the reverb.', 'Ustawia poziom suchego sygnału przez reverb.'),
  reverbWet: d('Sets the reverberated signal level.', 'Ustawia poziom sygnału pogłosu.'),
  reverbCorrelate: d('Adjusts stereo correlation of the reverb.', 'Reguluje korelację stereo pogłosu.'),
  reverbOutput: d('Sets the overall reverb module output level.', 'Ustawia ogólny poziom wyjściowy modułu reverb.'),
  reverbLimit: d('Limits the reverb return to prevent overload.', 'Ogranicza powrót pogłosu, aby uniknąć przesterowania.'),
  motionDepth: d('How far grain position wanders over time.', 'Jak daleko pozycja ziaren wędruje w czasie.'),
  motionRate: d('How quickly grain position motion moves.', 'Jak szybko porusza się wędrówka pozycji ziaren.'),
  motionJitter: d('Adds irregular motion to grain position.', 'Dodaje nieregularny ruch pozycji ziaren.'),
  outputGain: d('Sets the final output level of the instrument.', 'Ustawia końcowy poziom wyjściowy instrumentu.'),
  saturation: d('Adds harmonic saturation and drive.', 'Dodaje nasycenie harmoniczne i drive.'),
  saturationMix: d('Blends saturated signal with the clean signal.', 'Miesza sygnał nasycony z czystym.'),
  distortionTone: d('Shapes the brightness of the distortion.', 'Kształtuje jasność zniekształcenia.'),
  distortionBias: d('Offsets the distortion transfer for asymmetric grit.', 'Przesuwa charakterystykę zniekształcenia w stronę asymetrycznego brudu.'),
  distortionBits: d('Reduces bit depth for digital crushing.', 'Obniża głębię bitową, tworząc digital crush.'),
  distortionDownsample: d('Reduces sample rate for aliasing and lo-fi texture.', 'Obniża częstotliwość próbkowania, dodając aliasing i lo-fi.'),
  distortionNoise: d('Adds noise into the distortion path.', 'Dodaje szum do toru zniekształcenia.'),
  distortionOutput: d('Sets the distortion module output level.', 'Ustawia poziom wyjściowy modułu zniekształcenia.'),
  reverbSize: d('Sets the perceived size of the reverberant space.', 'Ustawia odczuwalną wielkość przestrzeni pogłosu.'),
  reverbDecay: d('Sets how long the reverberation lasts.', 'Ustawia, jak długo trwa pogłos.'),
  reverbPredelay: d('Delays the onset of the reverb relative to the dry signal.', 'Opóźnia początek pogłosu względem sygnału suchego.'),
  reverbDamping: d('Absorbs high frequencies in the reverb tail.', 'Tłumi wysokie częstotliwości w ogonie pogłosu.'),
  bpm: d('Sets the tempo used by synced time values.', 'Ustawia tempo używane przez zsynchronizowane wartości czasu.'),
  delaySync: d('Locks the left delay time to tempo.', 'Synchronizuje lewy czas delay z tempem.'),
  delayNote: d('Sets the synced note length of the left delay.', 'Ustawia długość nuty zsynchronizowanego lewego delay.'),
  delayNoteKind: d('Chooses dotted or triplet values for the left delay.', 'Wybiera wartości z kropką lub triole dla lewego delay.'),
  delaySyncR: d('Locks the right delay time to tempo.', 'Synchronizuje prawy czas delay z tempem.'),
  delayNoteR: d('Sets the synced note length of the right delay.', 'Ustawia długość nuty zsynchronizowanego prawego delay.'),
  delayNoteKindR: d('Chooses dotted or triplet values for the right delay.', 'Wybiera wartości z kropką lub triole dla prawego delay.'),
  delayWidth: d('Sets stereo width of the delay return.', 'Ustawia szerokość stereo powrotu delay.'),
  delayPan: d('Pans the delay return in the stereo field.', 'Panoramuje powrót delay w polu stereo.'),
  delayOffset: d('Offsets one delay side in time for stereo depth.', 'Przesuwa jedną stronę delay w czasie, pogłębiając stereo.'),
  delayHp: d('High-pass filters the delay feedback path.', 'Filtruje górnoprzepustowo pętlę sprzężenia delay.'),
  delayLp: d('Low-pass filters the delay feedback path.', 'Filtruje dolnoprzepustowo pętlę sprzężenia delay.'),
  delayDrive: d('Adds saturation in the delay feedback loop.', 'Dodaje nasycenie w pętli sprzężenia delay.'),
  delayModRate: d('Sets the delay modulation speed.', 'Ustawia prędkość modulacji delay.'),
  delayModDepth: d('Sets how much delay time is modulated.', 'Ustawia głębokość modulacji czasu delay.'),
  delayWow: d('Adds slow pitch drift in the delay.', 'Dodaje powolne kołysanie wysokości w delay.'),
  delayFlutter: d('Adds fast pitch flutter in the delay.', 'Dodaje szybkie kołysanie wysokości w delay.'),
  delayDiffusion: d('Smears delay repeats into a denser texture.', 'Rozmywa powtórzenia delay w gęstszą fakturę.'),
  delayPitch: d('Shifts the pitch of delay repeats.', 'Przesuwa wysokość powtórzeń delay.'),
  delayReverse: d('Reverses delay repeats.', 'Odwraca powtórzenia delay.'),
  delayDuck: d('Lowers delay level while the input is loud.', 'Obniża poziom delay, gdy wejście jest głośne.'),
  delayFreeze: d('Holds the current delay buffer.', 'Zatrzymuje bieżący bufor delay.'),
  delayDrift: d('Adds slow instability to delay time.', 'Dodaje powolną niestabilność czasu delay.'),
  reverbSync: d('Locks reverb time values to tempo.', 'Synchronizuje wartości czasu pogłosu z tempem.'),
  reverbNote: d('Sets the synced note length related to reverb time.', 'Ustawia długość nuty powiązaną z czasem pogłosu.'),
  reverbNoteKind: d('Chooses dotted or triplet values for synced reverb time.', 'Wybiera wartości z kropką lub triole dla zsynchronizowanego pogłosu.'),
  reverbEarly: d('Sets the level of early reflections.', 'Ustawia poziom wczesnych odbić.'),
  reverbDiffusion: d('Smears reflections into a smoother wash.', 'Rozmywa odbicia w gładszy pogłos.'),
  reverbDensity: d('Sets how dense the reverb texture is.', 'Ustawia gęstość faktury pogłosu.'),
  reverbLowCut: d('Removes low frequencies from the reverb.', 'Usuwa niskie częstotliwości z pogłosu.'),
  reverbHighCut: d('Removes high frequencies from the reverb.', 'Usuwa wysokie częstotliwości z pogłosu.'),
  reverbWidth: d('Sets stereo width of the reverb.', 'Ustawia szerokość stereo pogłosu.'),
  reverbPan: d('Pans the reverb return.', 'Panoramuje powrót pogłosu.'),
  reverbOffset: d('Offsets one reverb side in time.', 'Przesuwa jedną stronę pogłosu w czasie.'),
  reverbInput: d('Sets how much signal enters the reverb.', 'Ustawia, ile sygnału wchodzi do pogłosu.'),
  reverbStereo: d('Sets stereo spread inside the reverb algorithm.', 'Ustawia rozpiętość stereo wewnątrz algorytmu pogłosu.'),
  reverbModRate: d('Sets reverb modulation speed.', 'Ustawia prędkość modulacji pogłosu.'),
  reverbModDepth: d('Sets how much the reverb is modulated.', 'Ustawia głębokość modulacji pogłosu.'),
  reverbShimmerPitch: d('Sets the pitch interval of the shimmer layer.', 'Ustawia interwał wysokości warstwy shimmer.'),
  reverbShimmer: d('Adds pitched octave shimmer into the reverb.', 'Dodaje do pogłosu warstwę o przesuniętej wysokości.'),
  reverbDrive: d('Adds saturation to the reverb.', 'Dodaje nasycenie do pogłosu.'),
  reverbDuck: d('Lowers reverb level while the input is loud.', 'Obniża poziom pogłosu, gdy wejście jest głośne.'),
  reverbGate: d('Applies a gate to the reverb tail.', 'Nakłada bramkę na ogon pogłosu.'),
  reverbGateThres: d('Sets the level where the reverb gate opens.', 'Ustawia próg otwarcia bramki pogłosu.'),
  reverbGateAttack: d('Sets how quickly the reverb gate opens.', 'Ustawia, jak szybko otwiera się bramka pogłosu.'),
  reverbGateHold: d('Sets how long the reverb gate stays open.', 'Ustawia, jak długo bramka pogłosu pozostaje otwarta.'),
  reverbGateRelease: d('Sets how quickly the reverb gate closes.', 'Ustawia, jak szybko zamyka się bramka pogłosu.'),
  reverbReverse: d('Reverses the reverb tail.', 'Odwraca ogon pogłosu.'),
  reverbFreeze: d('Holds the current reverb tail.', 'Zatrzymuje bieżący ogon pogłosu.'),
  reverbColor: d('Shifts the tonal color of the reverb.', 'Zmienia barwę pogłosu.'),
  reverbDistance: d('Pushes the reverb farther from the source.', 'Oddala pogłos od źródła dźwięku.'),
  limiterThreshold: d('Sets the level where the limiter starts reducing gain.', 'Ustawia poziom, od którego limiter zaczyna redukować wzmocnienie.'),
  limiterCeiling: d('Sets the maximum output ceiling of the limiter.', 'Ustawia maksymalny pułap wyjściowy limitera.'),
  limiterRelease: d('Sets how quickly the limiter stops reducing gain.', 'Ustawia, jak szybko limiter przestaje redukować wzmocnienie.'),
  limiterAttack: d('Sets how quickly the limiter reacts to peaks.', 'Ustawia, jak szybko limiter reaguje na szczyty.'),
  limiterKnee: d('Softens the onset of limiting around the threshold.', 'Łagodzi początek limitowania wokół progu.'),
  limiterRatio: d('Sets how strongly the limiter compresses above the threshold.', 'Ustawia, jak mocno limiter kompresuje powyżej progu.'),
  limiterMakeup: d('Adds gain after limiting.', 'Dodaje wzmocnienie po limitowaniu.'),
  limiterInput: d('Sets the limiter input level.', 'Ustawia poziom wejściowy limitera.'),
  limiterAutoMakeup: d('Automatically compensates level after limiting.', 'Automatycznie wyrównuje poziom po limitowaniu.'),
  compressorThreshold: d('Sets the level where compression begins.', 'Ustawia poziom, od którego zaczyna się kompresja.'),
  compressorRatio: d('Sets how much the compressor reduces level above the threshold.', 'Ustawia, jak mocno kompresor obniża poziom powyżej progu.'),
  compressorKnee: d('Softens the onset of compression around the threshold.', 'Łagodzi początek kompresji wokół progu.'),
  compressorAttack: d('Sets how quickly the compressor reacts.', 'Ustawia, jak szybko reaguje kompresor.'),
  compressorRelease: d('Sets how quickly the compressor returns to unity.', 'Ustawia, jak szybko kompresor wraca do jedności.'),
  compressorMakeup: d('Adds gain after compression.', 'Dodaje wzmocnienie po kompresji.'),
  compressorInput: d('Sets the compressor input level.', 'Ustawia poziom wejściowy kompresora.'),
  compressorAutoMakeup: d('Automatically compensates level after compression.', 'Automatycznie wyrównuje poziom po kompresji.'),
  ...eqBandEntries(),
  eqcfTeeth: d('Sets how many notches the comb filter uses.', 'Ustawia liczbę wcięć filtra grzebieniowego.'),
  eqcfGain: d('Sets the depth of the comb filter notches.', 'Ustawia głębokość wcięć filtra grzebieniowego.'),
  eqcfSpacing: d('Sets the spacing between comb filter notches.', 'Ustawia odstęp między wcięciami filtra grzebieniowego.'),
  eqcfFreq: d('Sets the base frequency of the comb filter.', 'Ustawia częstotliwość bazową filtra grzebieniowego.'),
  msWidth: d('Widens or narrows the side component of the stereo image.', 'Poszerza lub zwęża składową side obrazu stereo.'),
  msBalance: d('Balances mid versus side energy.', 'Równoważy energię mid względem side.'),
  msMidGain: d('Sets the level of the mid (center) signal.', 'Ustawia poziom sygnału mid (środka).'),
  msSideGain: d('Sets the level of the side (stereo) signal.', 'Ustawia poziom sygnału side (stereo).'),
  msSideHpf: d('High-pass filters the side signal.', 'Filtruje górnoprzepustowo sygnał side.'),
  msMidTilt: d('Tilts the mid signal from dark to bright.', 'Pochyla barwę sygnału mid od ciemnej do jasnej.'),
  msSideTilt: d('Tilts the side signal from dark to bright.', 'Pochyla barwę sygnału side od ciemnej do jasnej.'),
  msMidLowFreq: d('Sets the low-band frequency for the mid equalizer.', 'Ustawia częstotliwość pasma niskiego korektora mid.'),
  msMidLowGain: d('Boosts or cuts low frequencies in the mid signal.', 'Podbija lub tłumi niskie częstotliwości sygnału mid.'),
  msMidPeakFreq: d('Sets the mid-band peak frequency for the mid equalizer.', 'Ustawia częstotliwość szczytu pasma środkowego korektora mid.'),
  msMidPeakGain: d('Boosts or cuts the mid-band peak in the mid signal.', 'Podbija lub tłumi szczyt pasma środkowego sygnału mid.'),
  msMidPeakQ: d('Sets the width of the mid-band peak in the mid signal.', 'Ustawia szerokość szczytu pasma środkowego sygnału mid.'),
  msMidHighFreq: d('Sets the high-band frequency for the mid equalizer.', 'Ustawia częstotliwość pasma wysokiego korektora mid.'),
  msMidHighGain: d('Boosts or cuts high frequencies in the mid signal.', 'Podbija lub tłumi wysokie częstotliwości sygnału mid.'),
  msSideLowFreq: d('Sets the low-band frequency for the side equalizer.', 'Ustawia częstotliwość pasma niskiego korektora side.'),
  msSideLowGain: d('Boosts or cuts low frequencies in the side signal.', 'Podbija lub tłumi niskie częstotliwości sygnału side.'),
  msSidePeakFreq: d('Sets the mid-band peak frequency for the side equalizer.', 'Ustawia częstotliwość szczytu pasma środkowego korektora side.'),
  msSidePeakGain: d('Boosts or cuts the mid-band peak in the side signal.', 'Podbija lub tłumi szczyt pasma środkowego sygnału side.'),
  msSidePeakQ: d('Sets the width of the mid-band peak in the side signal.', 'Ustawia szerokość szczytu pasma środkowego sygnału side.'),
  msSideHighFreq: d('Sets the high-band frequency for the side equalizer.', 'Ustawia częstotliwość pasma wysokiego korektora side.'),
  msSideHighGain: d('Boosts or cuts high frequencies in the side signal.', 'Podbija lub tłumi wysokie częstotliwości sygnału side.'),
  msRotate: d('Rotates the stereo image.', 'Obraca obraz stereo.'),
  msCrossfeed: d('Blends left and right into each other.', 'Miesza lewy i prawy kanał ze sobą.'),
  msHaasTime: d('Sets the delay used by the Haas stereo effect.', 'Ustawia opóźnienie efektu Haasa.'),
  msHaasAmount: d('Sets how strong the Haas stereo effect is.', 'Ustawia siłę efektu Haasa.'),
  msHaasDir: d('Chooses which side the Haas delay is applied to.', 'Wybiera stronę, na którą działa opóźnienie Haasa.'),
  msSoloMid: d('Solos the mid signal.', 'Włącza solo sygnału mid.'),
  msSoloSide: d('Solos the side signal.', 'Włącza solo sygnału side.'),
  msMono: d('Collapses the mid/side path to mono.', 'Zawęża tor mid/side do mono.'),
  msFlipMid: d('Inverts polarity of the mid signal.', 'Odwraca polaryzację sygnału mid.'),
  msFlipSide: d('Inverts polarity of the side signal.', 'Odwraca polaryzację sygnału side.'),
} as Record<ParamId, LocalizedText>

export const SENSORY_DESCRIPTIONS: Record<SensoryAxisId, LocalizedText> = {
  character: d('Shapes tonal character from tight to open.', 'Kształtuje charakter barwy od ciasnego do otwartego.'),
  space: d('Opens a reverberant space around the sound.', 'Otwiera przestrzeń pogłosu wokół dźwięku.'),
  echo: d('Adds repeating echoes after the sound.', 'Dodaje powtarzające się echa po dźwięku.'),
  grain: d('Breaks the sound into layered grains.', 'Rozbija dźwięk na warstwowe ziarna.'),
  dirt: d('Adds grit and distortion.', 'Dodaje brud i zniekształcenie.'),
  tight: d('Compresses dynamics to make the sound tighter.', 'Kompresuje dynamikę, zagęszczając dźwięk.'),
  mod: d('Adds movement and modulation.', 'Dodaje ruch i modulację.'),
  drift: d('Adds slow instability and wander.', 'Dodaje powolną niestabilność i dryf.'),
  pan: d('Moves the sound in the stereo field.', 'Przesuwa dźwięk w polu stereo.'),
  veil: d('Softens and blurs high-frequency detail.', 'Zmiękcza i zaciera detale wysokich częstotliwości.'),
  halo: d('Adds a bright halo around the sound.', 'Dodaje jasną poświatę wokół dźwięku.'),
  well: d('Pushes the sound into a deeper well of space.', 'Wciąga dźwięk w głębszą studnię przestrzeni.'),
  bloom: d('Lets the sound bloom outward.', 'Pozwala dźwiękowi rozkwitnąć na zewnątrz.'),
  plate: d('Adds a plate-like reverberation.', 'Dodaje pogłos o charakterze płyty.'),
  spring: d('Adds spring-like reverberation.', 'Dodaje pogłos o charakterze sprężyny.'),
  shimmer: d('Adds a pitched shimmer above the sound.', 'Dodaje błysk o przesuniętej wysokości nad dźwiękiem.'),
  reverse: d('Blends in reversed tails.', 'Domiesza odwrócone ogony dźwięku.'),
  gate: d('Gates the space so tails cut off abruptly.', 'Bramkuje przestrzeń, gwałtownie obcinając ogony.'),
  fuzz: d('Adds fuzzy distortion.', 'Dodaje puszyste zniekształcenie.'),
  crush: d('Crushes bit depth and sample rate.', 'Niszczy głębię bitową i częstotliwość próbkowania.'),
  tape: d('Adds tape-like saturation and warble.', 'Dodaje nasycenie i kołysanie taśmy.'),
  fold: d('Folds the waveform for harsh harmonics.', 'Składa przebieg, tworząc ostre harmoniczne.'),
  vinyl: d('Adds vinyl noise and wear.', 'Dodaje szum i zużycie winylu.'),
  sweep: d('Sweeps a filter across the spectrum.', 'Przeciąga filtr przez widmo.'),
  dark: d('Darkens the tone by removing brightness.', 'Przyciemnia barwę, usuwając jasność.'),
  thin: d('Thins the body of the sound.', 'Odchudza korpus dźwięku.'),
  phone: d('Narrows the band like a telephone.', 'Zwęża pasmo jak w telefonie.'),
  notch: d('Cuts a narrow band out of the tone.', 'Wycina wąskie pasmo z barwy.'),
  peak: d('Boosts a focused band in the tone.', 'Podbija skupione pasmo barwy.'),
  comb: d('Adds comb-filter ridges to the spectrum.', 'Dodaje grzebieniowe wcięcia w widmie.'),
  melt: d('Melts pitch and time stability.', 'Rozpuszcza stabilność wysokości i czasu.'),
}

export function paramDescription(id: ParamId, locale: Locale): string {
  return PARAM_DESCRIPTIONS[id]?.[locale] ?? PARAMS[id]?.label ?? id
}

export function sensoryDescription(id: SensoryAxisId, locale: Locale): string {
  return SENSORY_DESCRIPTIONS[id]?.[locale] ?? id
}
