import type { EffectMorph } from './morph'

/** Designed absolute stops. Rest (t≈0) leaves the captured DSP untouched. */
export const EFFECT_MORPHS: readonly EffectMorph[] = [
  {
    axis: 'character',
    module: 'eq',
    stops: [
      {
        t: -1,
        eq: [
          { band: 0, type: 'highpass', frequency: 180, gain: 0, q: 0.75 },
          { band: 1, type: 'peaking', frequency: 880, gain: 3.4, q: 1.35 },
          { band: 2, type: 'peaking', frequency: 3100, gain: 2.4, q: 1.5 },
          { band: 3, type: 'highshelf', frequency: 6400, gain: -5.4, q: 0.7 },
        ],
      },
      {
        t: -0.5,
        eq: [
          { band: 0, type: 'highpass', frequency: 95, gain: 0, q: 0.72 },
          { band: 1, type: 'peaking', frequency: 720, gain: 1.8, q: 1.15 },
          { band: 2, type: 'peaking', frequency: 2700, gain: 1.1, q: 1.2 },
          { band: 3, type: 'highshelf', frequency: 7800, gain: -2.6, q: 0.7 },
        ],
      },
      {
        t: 0,
        eq: [
          { band: 0, type: 'off', frequency: 80, gain: 0, q: 0.7 },
          { band: 1, type: 'off', frequency: 400, gain: 0, q: 1 },
          { band: 2, type: 'off', frequency: 2500, gain: 0, q: 1 },
          { band: 3, type: 'off', frequency: 12000, gain: 0, q: 0.7 },
        ],
      },
      {
        t: 0.5,
        eq: [
          { band: 0, type: 'lowshelf', frequency: 90, gain: 1.5, q: 0.7 },
          { band: 1, type: 'peaking', frequency: 420, gain: -0.8, q: 0.9 },
          { band: 2, type: 'peaking', frequency: 3400, gain: 1.3, q: 1.05 },
          { band: 3, type: 'highshelf', frequency: 10200, gain: 2.4, q: 0.7 },
        ],
      },
      {
        t: 1,
        eq: [
          { band: 0, type: 'lowshelf', frequency: 85, gain: 2.4, q: 0.7 },
          { band: 1, type: 'peaking', frequency: 430, gain: -1.4, q: 0.85 },
          { band: 2, type: 'peaking', frequency: 3500, gain: 2.1, q: 1.05 },
          { band: 3, type: 'highshelf', frequency: 11000, gain: 4.6, q: 0.65 },
        ],
      },
    ],
  },
  {
    axis: 'space',
    module: 'reverb',
    reverbType: 'hall',
    stops: [
      {
        t: 0,
        params: {
          reverbWet: 0,
          reverbSize: 46,
          reverbDecay: 1.1,
          reverbPredelay: 12,
          reverbWidth: 110,
          reverbDistance: 22,
          reverbEarly: 48,
          reverbDiffusion: 52,
          reverbShimmer: 0,
          reverbModDepth: 6,
          reverbHighCut: 11000,
          reverbColor: 0,
        },
      },
      {
        t: 0.22,
        params: {
          reverbWet: 14,
          reverbSize: 56,
          reverbDecay: 1.8,
          reverbPredelay: 18,
          reverbWidth: 122,
          reverbDistance: 28,
          reverbEarly: 56,
          reverbDiffusion: 60,
          reverbShimmer: 0,
          reverbModDepth: 8,
          reverbHighCut: 9800,
          reverbColor: 2,
        },
      },
      {
        t: 0.48,
        params: {
          reverbWet: 22,
          reverbSize: 66,
          reverbDecay: 2.6,
          reverbPredelay: 26,
          reverbWidth: 136,
          reverbDistance: 34,
          reverbEarly: 62,
          reverbDiffusion: 68,
          reverbShimmer: 2,
          reverbModDepth: 10,
          reverbHighCut: 8600,
          reverbColor: 4,
        },
      },
      {
        t: 0.74,
        params: {
          reverbWet: 30,
          reverbSize: 78,
          reverbDecay: 3.6,
          reverbPredelay: 34,
          reverbWidth: 148,
          reverbDistance: 40,
          reverbEarly: 68,
          reverbDiffusion: 74,
          reverbShimmer: 3,
          reverbModDepth: 12,
          reverbHighCut: 7600,
          reverbColor: 6,
        },
      },
      {
        t: 1,
        params: {
          reverbWet: 38,
          reverbSize: 88,
          reverbDecay: 4.8,
          reverbPredelay: 42,
          reverbWidth: 160,
          reverbDistance: 48,
          reverbEarly: 74,
          reverbDiffusion: 80,
          reverbShimmer: 4,
          reverbModDepth: 14,
          reverbHighCut: 6800,
          reverbColor: 8,
        },
      },
    ],
  },
  {
    axis: 'echo',
    module: 'delay',
    stops: [
      {
        t: 0,
        params: {
          delayWet: 0,
          delayFeedback: 35,
          delayTime: 300,
          delayWidth: 100,
          delayDiffusion: 0,
          delayOffset: 0,
        },
      },
      {
        t: 0.28,
        params: {
          delayWet: 14,
          delayFeedback: 32,
          delayTime: 240,
          delayWidth: 118,
          delayDiffusion: 10,
          delayOffset: 8,
        },
      },
      {
        t: 0.55,
        params: {
          delayWet: 28,
          delayFeedback: 32,
          delayTime: 390,
          delayWidth: 136,
          delayDiffusion: 18,
          delayOffset: 14,
        },
      },
      {
        t: 0.8,
        params: {
          delayWet: 38,
          delayFeedback: 36,
          delayTime: 520,
          delayWidth: 150,
          delayDiffusion: 24,
          delayOffset: 18,
        },
      },
      {
        t: 1,
        params: {
          delayWet: 46,
          delayFeedback: 38,
          delayTime: 640,
          delayWidth: 164,
          delayDiffusion: 30,
          delayOffset: 22,
        },
      },
    ],
  },
  {
    axis: 'grain',
    module: 'grain',
    stops: [
      {
        t: 0,
        params: {
          density: 18.4,
          scatter: 45,
          grainSize: 120,
          pitchSpread: 7.2,
        },
      },
      {
        t: 0.35,
        params: {
          density: 24,
          scatter: 52,
          grainSize: 150,
          pitchSpread: 5.5,
        },
      },
      {
        t: 0.7,
        params: {
          density: 34,
          scatter: 62,
          grainSize: 88,
          pitchSpread: 8.4,
        },
      },
      {
        t: 1,
        params: {
          density: 44,
          scatter: 72,
          grainSize: 58,
          pitchSpread: 10.5,
        },
      },
    ],
  },
  {
    axis: 'dirt',
    module: 'distortion',
    distortionType: 'saturation',
    stops: [
      { t: 0, params: { saturation: 0 } },
      { t: 0.4, params: { saturation: 12 } },
      { t: 0.72, params: { saturation: 22 } },
      { t: 1, params: { saturation: 34 } },
    ],
  },
  {
    axis: 'tight',
    module: 'compressor',
    stops: [
      {
        t: 0,
        params: {
          compressorThreshold: -6,
          compressorRatio: 2.4,
          compressorAttack: 12,
          compressorRelease: 180,
          compressorKnee: 14,
          compressorMakeup: 0,
        },
      },
      {
        t: 0.4,
        params: {
          compressorThreshold: -12,
          compressorRatio: 4.2,
          compressorAttack: 8,
          compressorRelease: 140,
          compressorKnee: 10,
          compressorMakeup: 1.2,
        },
      },
      {
        t: 0.72,
        params: {
          compressorThreshold: -18,
          compressorRatio: 7.5,
          compressorAttack: 3.5,
          compressorRelease: 110,
          compressorKnee: 5,
          compressorMakeup: 2.4,
        },
      },
      {
        t: 1,
        params: {
          compressorThreshold: -24,
          compressorRatio: 11,
          compressorAttack: 1.4,
          compressorRelease: 90,
          compressorKnee: 2.5,
          compressorMakeup: 3.6,
        },
      },
    ],
  },
  {
    axis: 'mod',
    module: 'grain',
    stops: [
      {
        t: 0,
        params: {
          motionDepth: 0,
          motionRate: 0.3,
          motionJitter: 30,
        },
      },
      {
        t: 0.35,
        params: {
          motionDepth: 22,
          motionRate: 0.45,
          motionJitter: 34,
        },
      },
      {
        t: 0.7,
        params: {
          motionDepth: 48,
          motionRate: 0.9,
          motionJitter: 42,
        },
      },
      {
        t: 1,
        params: {
          motionDepth: 72,
          motionRate: 1.6,
          motionJitter: 52,
        },
      },
    ],
  },
  {
    axis: 'drift',
    module: 'delay',
    stops: [
      {
        t: 0,
        params: {
          delayStereo: 1,
          delayWidth: 100,
          delayOffset: 0,
          delayPan: 0,
          delayModDepth: 0,
          delayModRate: 0.4,
          delayTime: 300,
          delayTimeR: 300,
          delayWet: 0,
          delayFeedback: 8,
        },
      },
      {
        t: 0.35,
        params: {
          delayStereo: 1,
          delayWidth: 142,
          delayOffset: 28,
          delayPan: 0,
          delayModDepth: 22,
          delayModRate: 0.7,
          delayTime: 18,
          delayTimeR: 28,
          delayWet: 16,
          delayFeedback: 8,
        },
      },
      {
        t: 0.7,
        params: {
          delayStereo: 1,
          delayWidth: 176,
          delayOffset: 46,
          delayPan: 0,
          delayModDepth: 30,
          delayModRate: 1.3,
          delayTime: 16,
          delayTimeR: 34,
          delayWet: 22,
          delayFeedback: 10,
        },
      },
      {
        t: 1,
        params: {
          delayStereo: 1,
          delayWidth: 200,
          delayOffset: 62,
          delayPan: 0,
          delayModDepth: 38,
          delayModRate: 1.9,
          delayTime: 14,
          delayTimeR: 42,
          delayWet: 28,
          delayFeedback: 12,
        },
      },
    ],
  },
  {
    axis: 'pan',
    module: 'gain',
    stops: [{ t: 0 }, { t: 1 }],
  },
  {
    axis: 'veil',
    module: 'reverb',
    modules: ['reverb', 'delay', 'eq'],
    reverbType: 'hall',
    stops: [
      {
        t: 0,
        params: {
          reverbWet: 0,
          reverbDistance: 22,
          reverbDamping: 18,
          reverbHighCut: 11000,
          delayWet: 0,
          delayTime: 90,
          delayFeedback: 12,
          delayDiffusion: 8,
        },
        eq: [
          { band: 2, type: 'off', frequency: 2400, gain: 0, q: 1 },
          { band: 3, type: 'off', frequency: 6500, gain: 0, q: 0.7 },
        ],
      },
      {
        t: 0.5,
        params: {
          reverbWet: 14,
          reverbDistance: 40,
          reverbDamping: 32,
          reverbHighCut: 7200,
          reverbSize: 62,
          reverbDecay: 2.2,
          delayWet: 10,
          delayTime: 96,
          delayFeedback: 16,
          delayDiffusion: 22,
        },
        eq: [
          { band: 2, type: 'peaking', frequency: 2200, gain: -1.4, q: 1.1 },
          { band: 3, type: 'highshelf', frequency: 6200, gain: -2.4, q: 0.7 },
        ],
      },
      {
        t: 1,
        params: {
          reverbWet: 24,
          reverbDistance: 58,
          reverbDamping: 46,
          reverbHighCut: 4800,
          reverbSize: 74,
          reverbDecay: 3.1,
          delayWet: 16,
          delayTime: 108,
          delayFeedback: 20,
          delayDiffusion: 36,
        },
        eq: [
          { band: 2, type: 'peaking', frequency: 2100, gain: -2.6, q: 1.2 },
          { band: 3, type: 'highshelf', frequency: 5800, gain: -4.2, q: 0.7 },
        ],
      },
    ],
  },
  {
    axis: 'halo',
    module: 'reverb',
    modules: ['reverb', 'delay', 'eq'],
    reverbType: 'cloud',
    stops: [
      {
        t: 0,
        params: {
          reverbWet: 0,
          reverbEarly: 48,
          reverbShimmer: 0,
          reverbHighCut: 11000,
          delayWet: 0,
          delayDiffusion: 0,
          delayTime: 210,
          delayFeedback: 10,
        },
        eq: [
          { band: 2, type: 'off', frequency: 3400, gain: 0, q: 1 },
          { band: 3, type: 'off', frequency: 10000, gain: 0, q: 0.7 },
        ],
      },
      {
        t: 0.5,
        params: {
          reverbWet: 12,
          reverbEarly: 68,
          reverbShimmer: 2,
          reverbSize: 60,
          reverbDecay: 2,
          reverbHighCut: 12500,
          delayWet: 8,
          delayDiffusion: 28,
          delayTime: 230,
          delayFeedback: 14,
        },
        eq: [
          { band: 2, type: 'peaking', frequency: 3600, gain: 1.2, q: 1.05 },
          { band: 3, type: 'highshelf', frequency: 9800, gain: 2.2, q: 0.65 },
        ],
      },
      {
        t: 1,
        params: {
          reverbWet: 20,
          reverbEarly: 82,
          reverbShimmer: 4,
          reverbSize: 70,
          reverbDecay: 2.6,
          reverbHighCut: 14000,
          delayWet: 12,
          delayDiffusion: 48,
          delayTime: 250,
          delayFeedback: 16,
        },
        eq: [
          { band: 2, type: 'peaking', frequency: 3800, gain: 2.1, q: 1.05 },
          { band: 3, type: 'highshelf', frequency: 10500, gain: 3.6, q: 0.62 },
        ],
      },
    ],
  },
  {
    axis: 'well',
    module: 'eq',
    modules: ['eq', 'reverb', 'delay'],
    reverbType: 'chamber',
    stops: [
      {
        t: 0,
        params: {
          reverbWet: 0,
          reverbSize: 46,
          reverbDecay: 1.1,
          delayWet: 0,
          delayTime: 140,
          delayFeedback: 10,
          delayOffset: 0,
        },
        eq: [
          { band: 0, type: 'off', frequency: 90, gain: 0, q: 0.7 },
          { band: 1, type: 'off', frequency: 480, gain: 0, q: 1 },
        ],
      },
      {
        t: 0.5,
        params: {
          reverbWet: 10,
          reverbSize: 68,
          reverbDecay: 2.4,
          delayWet: 8,
          delayTime: 150,
          delayFeedback: 14,
          delayOffset: 12,
        },
        eq: [
          { band: 0, type: 'lowshelf', frequency: 88, gain: 1.2, q: 0.7 },
          { band: 1, type: 'peaking', frequency: 520, gain: -2.6, q: 1.55 },
        ],
      },
      {
        t: 1,
        params: {
          reverbWet: 18,
          reverbSize: 84,
          reverbDecay: 3.4,
          delayWet: 14,
          delayTime: 168,
          delayFeedback: 18,
          delayOffset: 22,
        },
        eq: [
          { band: 0, type: 'lowshelf', frequency: 86, gain: 2, q: 0.7 },
          { band: 1, type: 'peaking', frequency: 490, gain: -4.8, q: 1.7 },
        ],
      },
    ],
  },
  {
    axis: 'bloom',
    module: 'reverb',
    reverbType: 'bloom',
    stops: [
      { t: 0, params: { reverbWet: 0, reverbSize: 70, reverbDecay: 2.2, reverbDiffusion: 70, reverbPredelay: 24 } },
      { t: 0.5, params: { reverbWet: 18, reverbSize: 82, reverbDecay: 3.6, reverbDiffusion: 84, reverbPredelay: 36, reverbModDepth: 22 } },
      { t: 1, params: { reverbWet: 32, reverbSize: 90, reverbDecay: 5, reverbDiffusion: 90, reverbPredelay: 48, reverbModDepth: 30, reverbWidth: 168 } },
    ],
  },
  {
    axis: 'plate',
    module: 'reverb',
    reverbType: 'plate',
    stops: [
      { t: 0, params: { reverbWet: 0, reverbSize: 42, reverbDecay: 0.9, reverbEarly: 50, reverbHighCut: 12000 } },
      { t: 0.5, params: { reverbWet: 20, reverbSize: 48, reverbDecay: 1.5, reverbEarly: 58, reverbColor: 16, reverbWidth: 138 } },
      { t: 1, params: { reverbWet: 34, reverbSize: 52, reverbDecay: 2.1, reverbEarly: 62, reverbColor: 28, reverbWidth: 150, reverbHighCut: 16000 } },
    ],
  },
  {
    axis: 'spring',
    module: 'reverb',
    reverbType: 'spring',
    stops: [
      { t: 0, params: { reverbWet: 0, reverbSize: 34, reverbDecay: 0.8, reverbDrive: 0, reverbWidth: 80 } },
      { t: 0.5, params: { reverbWet: 18, reverbSize: 38, reverbDecay: 1.2, reverbDrive: 8, reverbWidth: 86, reverbPredelay: 6 } },
      { t: 1, params: { reverbWet: 30, reverbSize: 42, reverbDecay: 1.5, reverbDrive: 14, reverbWidth: 90, reverbPredelay: 8, reverbColor: 12 } },
    ],
  },
  {
    axis: 'shimmer',
    module: 'reverb',
    reverbType: 'shimmer',
    stops: [
      { t: 0, params: { reverbWet: 0, reverbShimmer: 0, reverbShimmerPitch: 12, reverbSize: 64, reverbDecay: 2.4 } },
      { t: 0.5, params: { reverbWet: 16, reverbShimmer: 12, reverbShimmerPitch: 12, reverbSize: 72, reverbDecay: 3.4, reverbModDepth: 18 } },
      { t: 1, params: { reverbWet: 28, reverbShimmer: 24, reverbShimmerPitch: 12, reverbSize: 80, reverbDecay: 4.6, reverbModDepth: 26, reverbWidth: 170 } },
    ],
  },
  {
    axis: 'reverse',
    module: 'reverb',
    reverbType: 'reverse',
    stops: [
      { t: 0, params: { reverbWet: 0, reverbReverse: 0, reverbSize: 52, reverbDecay: 1.1, reverbPredelay: 40 } },
      { t: 0.5, params: { reverbWet: 16, reverbReverse: 70, reverbSize: 58, reverbDecay: 1.5, reverbPredelay: 70 } },
      { t: 1, params: { reverbWet: 28, reverbReverse: 100, reverbSize: 64, reverbDecay: 1.8, reverbPredelay: 90, reverbWidth: 155 } },
    ],
  },
  {
    axis: 'gate',
    module: 'reverb',
    reverbType: 'gated',
    stops: [
      { t: 0, params: { reverbWet: 0, reverbGate: 0, reverbSize: 48, reverbDecay: 0.5, reverbPredelay: 2 } },
      { t: 0.5, params: { reverbWet: 20, reverbGate: 48, reverbGateThres: -20, reverbSize: 52, reverbDecay: 0.62, reverbGateHold: 70 } },
      { t: 1, params: { reverbWet: 34, reverbGate: 78, reverbGateThres: -18, reverbSize: 56, reverbDecay: 0.72, reverbGateHold: 82, reverbGateRelease: 36, reverbWidth: 122 } },
    ],
  },
  {
    axis: 'fuzz',
    module: 'distortion',
    distortionType: 'fuzz',
    stops: [
      { t: 0, params: { saturation: 0, saturationMix: 100 } },
      { t: 0.45, params: { saturation: 14, saturationMix: 100 } },
      { t: 1, params: { saturation: 30, saturationMix: 100 } },
    ],
  },
  {
    axis: 'crush',
    module: 'distortion',
    distortionType: 'bitcrush',
    stops: [
      { t: 0, params: { saturation: 0, saturationMix: 100, distortionBits: 16, distortionDownsample: 1 } },
      { t: 0.5, params: { saturation: 10, saturationMix: 100, distortionBits: 10, distortionDownsample: 3 } },
      { t: 1, params: { saturation: 22, saturationMix: 100, distortionBits: 6, distortionDownsample: 6 } },
    ],
  },
  {
    axis: 'tape',
    module: 'distortion',
    distortionType: 'tape',
    stops: [
      { t: 0, params: { saturation: 0, saturationMix: 100 } },
      { t: 0.5, params: { saturation: 14, saturationMix: 100 } },
      { t: 1, params: { saturation: 28, saturationMix: 100, distortionNoise: 4 } },
    ],
  },
  {
    axis: 'fold',
    module: 'distortion',
    distortionType: 'fold',
    stops: [
      { t: 0, params: { saturation: 0, saturationMix: 100 } },
      { t: 0.5, params: { saturation: 12, saturationMix: 100 } },
      { t: 1, params: { saturation: 26, saturationMix: 100 } },
    ],
  },
  {
    axis: 'vinyl',
    module: 'distortion',
    distortionType: 'vinyl',
    stops: [
      { t: 0, params: { saturation: 0, saturationMix: 70, distortionNoise: 0 } },
      { t: 0.5, params: { saturation: 8, saturationMix: 80, distortionNoise: 8 } },
      { t: 1, params: { saturation: 16, saturationMix: 88, distortionNoise: 16 } },
    ],
  },
  {
    axis: 'sweep',
    module: 'filter',
    stops: [
      {
        t: 0,
        params: {
          filterKind: 0,
          filterCutoff: 12000,
          filterReso: 0.7,
          filterDrive: 0,
          filterMix: 100,
          filterLfoDepth: 0,
          filterEnvAmt: 0,
        },
      },
      {
        t: 0.5,
        params: {
          filterKind: 0,
          filterCutoff: 1400,
          filterReso: 3.6,
          filterDrive: 8,
          filterMix: 100,
          filterLfoDepth: 28,
          filterLfoRate: 0.22,
        },
      },
      {
        t: 1,
        params: {
          filterKind: 0,
          filterCutoff: 520,
          filterReso: 6.2,
          filterDrive: 14,
          filterMix: 100,
          filterLfoDepth: 55,
          filterLfoRate: 0.35,
          filterSlope: 3,
        },
      },
    ],
  },
]
