import type { FilterType, ParamDef, ParamId, PlaybackDirection } from './types'

export const PARAMS: Record<ParamId, ParamDef> = {
  start: {
    id: 'start',
    label: 'Start',
    min: 0,
    max: 1,
    defaultValue: 0,
    unit: 's',
    mapping: 'linear',
  },
  end: {
    id: 'end',
    label: 'End',
    min: 0,
    max: 1,
    defaultValue: 1,
    unit: 's',
    mapping: 'linear',
  },
  speed: {
    id: 'speed',
    label: 'Speed',
    min: 0.25,
    max: 4,
    defaultValue: 1,
    unit: 'x',
    mapping: 'log',
  },
  pitch: {
    id: 'pitch',
    label: 'Pitch',
    min: -24,
    max: 24,
    defaultValue: 0,
    unit: 'st',
    mapping: 'linear',
    step: 0.01,
  },
  gain: {
    id: 'gain',
    label: 'Gain',
    min: -24,
    max: 6,
    defaultValue: -3,
    unit: 'dB',
    mapping: 'linear',
    step: 0.1,
  },
  pan: {
    id: 'pan',
    label: 'Pan',
    min: -100,
    max: 100,
    defaultValue: 0,
    unit: '%',
    mapping: 'linear',
    step: 1,
  },
  channelGainL: {
    id: 'channelGainL',
    label: 'Left',
    min: -24,
    max: 6,
    defaultValue: 0,
    unit: 'dB',
    mapping: 'linear',
    step: 0.1,
  },
  channelGainR: {
    id: 'channelGainR',
    label: 'Right',
    min: -24,
    max: 6,
    defaultValue: 0,
    unit: 'dB',
    mapping: 'linear',
    step: 0.1,
  },
  makeMono: {
    id: 'makeMono',
    label: 'Mono',
    min: 0,
    max: 1,
    defaultValue: 0,
    unit: '',
    mapping: 'linear',
    step: 1,
  },
  invertPhase: {
    id: 'invertPhase',
    label: 'Invert Phase',
    min: 0,
    max: 1,
    defaultValue: 0,
    unit: '',
    mapping: 'linear',
    step: 1,
  },
  grainSize: {
    id: 'grainSize',
    label: 'Grain Size',
    min: 8,
    max: 800,
    defaultValue: 120,
    unit: 'ms',
    mapping: 'log',
  },
  density: {
    id: 'density',
    label: 'Density',
    min: 1,
    max: 80,
    defaultValue: 18.4,
    unit: 'Hz',
    mapping: 'log',
  },
  position: {
    id: 'position',
    label: 'Position',
    min: 0,
    max: 100,
    defaultValue: 32,
    unit: '%',
    mapping: 'linear',
  },
  scatter: {
    id: 'scatter',
    label: 'Scatter',
    min: 0,
    max: 100,
    defaultValue: 45,
    unit: '%',
    mapping: 'linear',
  },
  grainPitch: {
    id: 'grainPitch',
    label: 'Pitch',
    min: -24,
    max: 24,
    defaultValue: 0,
    unit: 'st',
    mapping: 'linear',
    step: 0.01,
  },
  pitchSpread: {
    id: 'pitchSpread',
    label: 'Pitch Spread',
    min: 0,
    max: 24,
    defaultValue: 7.2,
    unit: 'st',
    mapping: 'linear',
    step: 0.01,
  },
  filterCutoff: {
    id: 'filterCutoff',
    label: 'Cutoff',
    min: 10,
    max: 25000,
    // Open by default so engaging the filter starts transparent, then closes.
    defaultValue: 18000,
    unit: 'Hz',
    mapping: 'log',
  },
  filterReso: {
    id: 'filterReso',
    label: 'Resonance',
    min: 0.1,
    max: 18,
    defaultValue: 0.7,
    unit: 'Q',
    mapping: 'log',
    step: 0.01,
  },
  delayDry: {
    id: 'delayDry',
    label: 'Dry',
    min: 0,
    max: 100,
    defaultValue: 100,
    unit: '%',
    mapping: 'linear',
  },
  delayWet: {
    id: 'delayWet',
    label: 'Mix',
    min: 0,
    max: 100,
    defaultValue: 0,
    unit: '%',
    mapping: 'linear',
  },
  delayOutput: {
    id: 'delayOutput',
    label: 'Output',
    min: 0,
    max: 200,
    defaultValue: 100,
    unit: '%',
    mapping: 'linear',
  },
  delayTime: {
    id: 'delayTime',
    label: 'Time',
    min: 1,
    max: 10000,
    defaultValue: 300,
    unit: 'ms',
    mapping: 'log',
  },
  delayFeedback: {
    id: 'delayFeedback',
    label: 'Feedback',
    min: 0,
    max: 95,
    defaultValue: 35,
    unit: '%',
    mapping: 'linear',
  },
  reverbDry: {
    id: 'reverbDry',
    label: 'Dry',
    min: 0,
    max: 100,
    defaultValue: 100,
    unit: '%',
    mapping: 'linear',
  },
  reverbWet: {
    id: 'reverbWet',
    label: 'Mix',
    min: 0,
    max: 100,
    defaultValue: 0,
    unit: '%',
    mapping: 'linear',
  },
  reverbOutput: {
    id: 'reverbOutput',
    label: 'Output',
    min: 0,
    max: 200,
    defaultValue: 100,
    unit: '%',
    mapping: 'linear',
  },
  reverbLimit: {
    id: 'reverbLimit',
    label: 'Limit',
    min: 0,
    max: 24,
    defaultValue: 0,
    unit: 'dB',
    mapping: 'linear',
    step: 0.5,
  },
  motionDepth: {
    id: 'motionDepth',
    label: 'Depth',
    min: 0,
    max: 100,
    // Off by default so the grain position stays where you set it.
    defaultValue: 0,
    unit: '%',
    mapping: 'linear',
  },
  motionRate: {
    id: 'motionRate',
    label: 'Rate',
    min: 0.02,
    max: 8,
    defaultValue: 0.3,
    unit: 'Hz',
    mapping: 'log',
  },
  motionJitter: {
    id: 'motionJitter',
    label: 'Jitter',
    min: 0,
    max: 100,
    defaultValue: 30,
    unit: '%',
    mapping: 'linear',
  },
  outputGain: {
    id: 'outputGain',
    label: 'Output Gain',
    min: -24,
    max: 6,
    defaultValue: 0,
    unit: 'dB',
    mapping: 'linear',
    step: 0.1,
  },
  saturation: {
    id: 'saturation',
    label: 'Drive',
    min: 0,
    max: 100,
    defaultValue: 0,
    unit: '%',
    mapping: 'linear',
  },
  reverbSize: {
    id: 'reverbSize',
    label: 'Size',
    min: 0,
    max: 100,
    defaultValue: 50,
    unit: '%',
    mapping: 'linear',
  },
  reverbDecay: {
    id: 'reverbDecay',
    label: 'Decay',
    min: 0.05,
    max: 60,
    defaultValue: 1.6,
    unit: 's',
    mapping: 'log',
  },
  reverbPredelay: {
    id: 'reverbPredelay',
    label: 'Pre-Delay',
    min: 0.1,
    max: 1000,
    defaultValue: 18,
    unit: 'ms',
    mapping: 'log',
  },
  reverbDamping: {
    id: 'reverbDamping',
    label: 'Damping',
    min: 200,
    max: 18000,
    defaultValue: 7000,
    unit: 'Hz',
    mapping: 'log',
  },
  bpm: {
    id: 'bpm',
    label: 'BPM',
    min: 40,
    max: 240,
    defaultValue: 120,
    unit: 'bpm',
    mapping: 'linear',
    step: 0.1,
  },
  delaySync: {
    id: 'delaySync',
    label: 'Sync',
    min: 0,
    max: 1,
    defaultValue: 0,
    unit: '',
    mapping: 'linear',
    step: 1,
  },
  delayNote: {
    id: 'delayNote',
    label: 'Note',
    min: 0,
    max: 7,
    defaultValue: 4,
    unit: '',
    mapping: 'linear',
    step: 1,
  },
  delayNoteKind: {
    id: 'delayNoteKind',
    label: 'Feel',
    min: 0,
    max: 2,
    defaultValue: 0,
    unit: '',
    mapping: 'linear',
    step: 1,
  },
  delayWidth: {
    id: 'delayWidth',
    label: 'Width',
    min: 0,
    max: 200,
    defaultValue: 100,
    unit: '%',
    mapping: 'linear',
  },
  delayPan: {
    id: 'delayPan',
    label: 'Pan',
    min: -100,
    max: 100,
    defaultValue: 0,
    unit: '%',
    mapping: 'linear',
  },
  delayOffset: {
    id: 'delayOffset',
    label: 'L/R Offset',
    min: -100,
    max: 100,
    defaultValue: 0,
    unit: '%',
    mapping: 'linear',
  },
  delayHp: {
    id: 'delayHp',
    label: 'HP',
    min: 20,
    max: 10000,
    defaultValue: 20,
    unit: 'Hz',
    mapping: 'log',
  },
  delayLp: {
    id: 'delayLp',
    label: 'LP',
    min: 200,
    max: 20000,
    defaultValue: 20000,
    unit: 'Hz',
    mapping: 'log',
  },
  delayDrive: {
    id: 'delayDrive',
    label: 'Drive',
    min: 0,
    max: 100,
    defaultValue: 0,
    unit: '%',
    mapping: 'linear',
  },
  delayModRate: {
    id: 'delayModRate',
    label: 'Mod Rate',
    min: 0.01,
    max: 20,
    defaultValue: 0.4,
    unit: 'Hz',
    mapping: 'log',
  },
  delayModDepth: {
    id: 'delayModDepth',
    label: 'Mod Depth',
    min: 0,
    max: 100,
    defaultValue: 0,
    unit: '%',
    mapping: 'linear',
  },
  delayWow: {
    id: 'delayWow',
    label: 'Wow',
    min: 0,
    max: 100,
    defaultValue: 0,
    unit: '%',
    mapping: 'linear',
  },
  delayFlutter: {
    id: 'delayFlutter',
    label: 'Flutter',
    min: 0,
    max: 100,
    defaultValue: 0,
    unit: '%',
    mapping: 'linear',
  },
  delayDiffusion: {
    id: 'delayDiffusion',
    label: 'Diffusion',
    min: 0,
    max: 100,
    defaultValue: 0,
    unit: '%',
    mapping: 'linear',
  },
  delayPitch: {
    id: 'delayPitch',
    label: 'Pitch',
    min: -48,
    max: 48,
    defaultValue: 0,
    unit: 'st',
    mapping: 'linear',
    step: 0.01,
  },
  delayReverse: {
    id: 'delayReverse',
    label: 'Reverse',
    min: 0,
    max: 100,
    defaultValue: 0,
    unit: '%',
    mapping: 'linear',
  },
  delayDuck: {
    id: 'delayDuck',
    label: 'Duck',
    min: 0,
    max: 100,
    defaultValue: 0,
    unit: '%',
    mapping: 'linear',
  },
  delayFreeze: {
    id: 'delayFreeze',
    label: 'Freeze',
    min: 0,
    max: 1,
    defaultValue: 0,
    unit: '',
    mapping: 'linear',
    step: 1,
  },
  delayDrift: {
    id: 'delayDrift',
    label: 'Drift',
    min: 0,
    max: 100,
    defaultValue: 0,
    unit: '%',
    mapping: 'linear',
  },
  reverbSync: {
    id: 'reverbSync',
    label: 'Sync',
    min: 0,
    max: 1,
    defaultValue: 0,
    unit: '',
    mapping: 'linear',
    step: 1,
  },
  reverbNote: {
    id: 'reverbNote',
    label: 'Note',
    min: 0,
    max: 7,
    defaultValue: 4,
    unit: '',
    mapping: 'linear',
    step: 1,
  },
  reverbNoteKind: {
    id: 'reverbNoteKind',
    label: 'Feel',
    min: 0,
    max: 2,
    defaultValue: 0,
    unit: '',
    mapping: 'linear',
    step: 1,
  },
  reverbEarly: {
    id: 'reverbEarly',
    label: 'Early',
    min: 0,
    max: 100,
    defaultValue: 40,
    unit: '%',
    mapping: 'linear',
  },
  reverbDiffusion: {
    id: 'reverbDiffusion',
    label: 'Diffusion',
    min: 0,
    max: 100,
    defaultValue: 55,
    unit: '%',
    mapping: 'linear',
  },
  reverbDensity: {
    id: 'reverbDensity',
    label: 'Density',
    min: 0,
    max: 100,
    defaultValue: 70,
    unit: '%',
    mapping: 'linear',
  },
  reverbLowCut: {
    id: 'reverbLowCut',
    label: 'Low Cut',
    min: 20,
    max: 2000,
    defaultValue: 20,
    unit: 'Hz',
    mapping: 'log',
  },
  reverbHighCut: {
    id: 'reverbHighCut',
    label: 'High Cut',
    min: 1000,
    max: 20000,
    defaultValue: 16000,
    unit: 'Hz',
    mapping: 'log',
  },
  reverbWidth: {
    id: 'reverbWidth',
    label: 'Width',
    min: 0,
    max: 200,
    defaultValue: 100,
    unit: '%',
    mapping: 'linear',
  },
  reverbModRate: {
    id: 'reverbModRate',
    label: 'Mod Rate',
    min: 0.01,
    max: 12,
    defaultValue: 0.35,
    unit: 'Hz',
    mapping: 'log',
  },
  reverbModDepth: {
    id: 'reverbModDepth',
    label: 'Mod Depth',
    min: 0,
    max: 100,
    defaultValue: 8,
    unit: '%',
    mapping: 'linear',
  },
  reverbShimmerPitch: {
    id: 'reverbShimmerPitch',
    label: 'Shimmer Pitch',
    min: -24,
    max: 24,
    defaultValue: 12,
    unit: 'st',
    mapping: 'linear',
    step: 0.01,
  },
  reverbShimmer: {
    id: 'reverbShimmer',
    label: 'Shimmer',
    min: 0,
    max: 100,
    defaultValue: 0,
    unit: '%',
    mapping: 'linear',
  },
  reverbDrive: {
    id: 'reverbDrive',
    label: 'Drive',
    min: 0,
    max: 100,
    defaultValue: 0,
    unit: '%',
    mapping: 'linear',
  },
  reverbDuck: {
    id: 'reverbDuck',
    label: 'Duck',
    min: 0,
    max: 100,
    defaultValue: 0,
    unit: '%',
    mapping: 'linear',
  },
  reverbGate: {
    id: 'reverbGate',
    label: 'Gate',
    min: 0,
    max: 100,
    defaultValue: 0,
    unit: '%',
    mapping: 'linear',
  },
  reverbGateThres: {
    id: 'reverbGateThres',
    label: 'Threshold',
    min: -60,
    max: 0,
    defaultValue: -24,
    unit: 'dB',
    mapping: 'linear',
    step: 0.1,
  },
  reverbGateAttack: {
    id: 'reverbGateAttack',
    label: 'Attack',
    min: 0.1,
    max: 50,
    defaultValue: 1,
    unit: 'ms',
    mapping: 'log',
  },
  reverbGateHold: {
    id: 'reverbGateHold',
    label: 'Hold',
    min: 1,
    max: 500,
    defaultValue: 80,
    unit: 'ms',
    mapping: 'log',
  },
  reverbGateRelease: {
    id: 'reverbGateRelease',
    label: 'Release',
    min: 10,
    max: 2000,
    defaultValue: 120,
    unit: 'ms',
    mapping: 'log',
  },
  reverbReverse: {
    id: 'reverbReverse',
    label: 'Reverse',
    min: 0,
    max: 100,
    defaultValue: 0,
    unit: '%',
    mapping: 'linear',
  },
  reverbFreeze: {
    id: 'reverbFreeze',
    label: 'Freeze',
    min: 0,
    max: 1,
    defaultValue: 0,
    unit: '',
    mapping: 'linear',
    step: 1,
  },
  reverbColor: {
    id: 'reverbColor',
    label: 'Color',
    min: -100,
    max: 100,
    defaultValue: 0,
    unit: '%',
    mapping: 'linear',
  },
  reverbDistance: {
    id: 'reverbDistance',
    label: 'Distance',
    min: 0,
    max: 100,
    defaultValue: 35,
    unit: '%',
    mapping: 'linear',
  },
}

/** Filter type options, in UI order. `off` bypasses the filter entirely. */
export const FILTER_TYPES: { value: FilterType; label: string }[] = [
  { value: 'off', label: 'Off' },
  { value: 'lowpass', label: 'Low Pass' },
  { value: 'highpass', label: 'High Pass' },
  { value: 'lowshelf', label: 'Low Shelf' },
  { value: 'highshelf', label: 'High Shelf' },
  { value: 'peaking', label: 'Bell' },
  { value: 'notch', label: 'Notch' },
  { value: 'bandpass', label: 'Band Pass' },
]

/** Playback direction options for the region player. */
export const PLAYBACK_DIRECTIONS: { value: PlaybackDirection; label: string }[] = [
  { value: 'forward', label: 'Forward' },
  { value: 'reverse', label: 'Reverse' },
  { value: 'pingpong', label: 'Ping-Pong' },
]

export const PARAM_IDS = Object.keys(PARAMS) as ParamId[]

export const SOURCE_KNOBS: ParamId[] = ['speed', 'pitch', 'gain', 'pan']
export const GRAIN_KNOBS: ParamId[] = [
  'grainSize',
  'density',
  'position',
  'scatter',
  'grainPitch',
  'pitchSpread',
]
export const MOTION_KNOBS: ParamId[] = ['motionDepth', 'motionRate', 'motionJitter', 'position']
export const SPACE_KNOBS: ParamId[] = [
  'delayWet',
  'delayTime',
  'delayFeedback',
  'reverbWet',
  'reverbSize',
  'reverbDecay',
  'reverbLimit',
]
export const DELAY_MAIN_KNOBS: ParamId[] = ['delayWet', 'delayTime', 'delayFeedback']
export const REVERB_MAIN_KNOBS: ParamId[] = [
  'reverbWet',
  'reverbSize',
  'reverbDecay',
  'reverbLimit',
]
export const FILTER_KNOBS: ParamId[] = ['filterCutoff', 'filterReso']
export const OUTPUT_KNOBS: ParamId[] = ['gain']

export function defaultParamValues(): Record<ParamId, number> {
  const values = {} as Record<ParamId, number>
  for (const id of PARAM_IDS) {
    values[id] = PARAMS[id].defaultValue
  }
  return values
}
